import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import {
  ArrowDownToLine, ArrowUpRight, BarChart3, BookOpenText, Check, ChevronRight, CircleAlert, CircleCheck, ClipboardPenLine,
  Copy, FileJson2, FileSpreadsheet, Gauge, Lightbulb, LineChart, Loader2, MoreHorizontal, Pencil, Plus, Rocket, Save,
  Settings2, Sparkles, Target, Trash2, TrendingUp, WandSparkles,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

type IdeaForm = { title: string; summary: string; category: string; tags: string; sourceUrl: string; personalExperience: string; targetUser: string; angle: string; priority: "low" | "medium" | "high"; status: "unused" | "drafting" | "published" | "archived" };
type ResultForm = { title: string; category: string; postUrl: string; postedAt: string; impressions: number; engagements: number; likes: number; replies: number; reposts: number; bookmarks: number; clicks: number; notes: string };
const blankIdea: IdeaForm = { title: "", summary: "", category: "AI × 業務効率化", tags: "", sourceUrl: "", personalExperience: "", targetUser: "", angle: "", priority: "medium", status: "unused" };
const blankResult = (): ResultForm => ({ title: "", category: "AI × 業務効率化", postUrl: "", postedAt: new Date().toISOString().slice(0, 16), impressions: 0, engagements: 0, likes: 0, replies: 0, reposts: 0, bookmarks: 0, clicks: 0, notes: "" });
const categoryColors = ["#49657e", "#a8c4a2", "#d6aa55", "#b799b3", "#d98d68"];

function formatNumber(value: number) { return new Intl.NumberFormat("ja-JP", { notation: value >= 10000 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value); }
function formatDate(value: Date | string) { return new Intl.DateTimeFormat("ja-JP", { month: "short", day: "numeric" }).format(new Date(value)); }
function rate(value: number) { return `${value.toFixed(2)}%`; }
function download(filename: string, contents: string, type: string) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([contents], { type })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
function csvCell(value: unknown) { const text = typeof value === "string" ? value : JSON.stringify(value ?? ""); return `"${text.replaceAll('"', '""')}"`; }

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="flex flex-col gap-5 border-b border-border/70 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="editorial-title mt-2 text-3xl font-bold text-foreground sm:text-[2.3rem]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{description}</p></div>{action && <div className="shrink-0">{action}</div>}</div>;
}

function EmptyState({ icon: Icon, title, description, action }: { icon: typeof Sparkles; title: string; description: string; action?: React.ReactNode }) {
  return <div className="flex min-h-[250px] flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card/55 px-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-secondary text-primary"><Icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm leading-relaxed text-muted-foreground">{description}</p>{action && <div className="mt-4">{action}</div>}</div>;
}

function AuthGate({ children }: { children: React.ReactNode }) {
  const { isAuthenticated, loading } = useAuth();
  if (loading) return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;
  if (!isAuthenticated) return <div className="container py-8 lg:py-12"><div className="soft-card mx-auto max-w-2xl rounded-3xl p-8 text-center sm:p-12"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-primary text-primary-foreground"><Sparkles className="h-6 w-6" /></div><p className="eyebrow mt-7">Private workspace</p><h1 className="editorial-title mt-2 text-3xl font-bold">あなたの運用ログを、資産にする。</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-muted-foreground">SNS Growth Copilotは、ネタ・投稿案・実績・改善ルールを一元管理する個人用ワークスペースです。保存やAI生成を始めるにはログインしてください。</p><Button onClick={() => startLogin()} size="lg" className="mt-7 rounded-xl bg-primary px-6 shadow-lg shadow-primary/20"><Rocket className="mr-2 h-4 w-4" />ログインしてワークスペースを開く</Button></div></div>;
  return <>{children}</>;
}

function Overview() {
  const { isAuthenticated } = useAuth();
  const dashboard = trpc.growth.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const [, setLocation] = useLocation();
  const summary = dashboard.data?.summary;
  const trend = dashboard.data?.trend ?? [];
  const categories = dashboard.data?.categoryBreakdown ?? [];
  const imProgress = summary ? Math.min(100, (summary.impressions / summary.impressionsTarget) * 100) : 0;
  const erProgress = summary ? Math.min(100, (summary.engagementRate / summary.engagementRateTarget) * 100) : 0;
  return <div className="container py-8 lg:py-11"><PageHeader eyebrow="Growth workspace / 01" title="投稿活動を、成長の循環へ。" description="日々の発信を記録し、確かな手応えを次の一案へとつなげます。" action={<Button onClick={() => setLocation("/drafts")} className="rounded-xl bg-primary px-5 shadow-lg shadow-primary/15"><WandSparkles className="mr-2 h-4 w-4" />投稿案をつくる</Button>} />
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard label="総インプレッション" value={formatNumber(summary?.impressions ?? 0)} detail={`目標 ${formatNumber(summary?.impressionsTarget ?? 0)}`} icon={TrendingUp} accent="blue" />
      <MetricCard label="エンゲージメント率" value={rate(summary?.engagementRate ?? 0)} detail={`目標 ${rate(summary?.engagementRateTarget ?? 0)}`} icon={Gauge} accent="green" />
      <MetricCard label="投稿数" value={`${summary?.postCount ?? 0}`} detail="記録済みの投稿" icon={ClipboardPenLine} accent="gold" />
      <MetricCard label="育成中のネタ" value={`${summary?.ideaCount ?? 0}`} detail="まだ使っていないアイデア" icon={Lightbulb} accent="violet" />
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_.85fr]">
      <Card className="soft-card overflow-hidden rounded-2xl"><CardContent className="p-0"><div className="flex items-start justify-between px-6 pt-6"><div><p className="eyebrow">Momentum</p><h2 className="mt-1 text-lg font-bold">直近14日間のリーチ推移</h2></div><Badge variant="secondary" className="rounded-full bg-secondary px-3 py-1 text-[10px]">実績データ</Badge></div><div className="h-[265px] px-2 pt-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ left: 0, right: 12, top: 8, bottom: 0 }}><defs><linearGradient id="impressions" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#49657e" stopOpacity={.38} /><stop offset="100%" stopColor="#49657e" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5e0d6" strokeDasharray="4 4" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#718096" }} /><YAxis hide /><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #e5e0d6", fontSize: 12 }} formatter={(value: number) => [formatNumber(value), "インプレッション"]} /><Area type="monotone" dataKey="impressions" stroke="#49657e" strokeWidth={2.2} fill="url(#impressions)" /></AreaChart></ResponsiveContainer></div></CardContent></Card>
      <Card className="soft-card rounded-2xl"><CardContent className="p-6"><p className="eyebrow">Goal pulse</p><h2 className="mt-1 text-lg font-bold">今週のKPI</h2><div className="mt-7 space-y-6"><GoalProgress label="インプレッション" value={formatNumber(summary?.impressions ?? 0)} target={formatNumber(summary?.impressionsTarget ?? 0)} progress={imProgress} color="bg-[#49657e]" /><GoalProgress label="エンゲージメント率" value={rate(summary?.engagementRate ?? 0)} target={rate(summary?.engagementRateTarget ?? 0)} progress={erProgress} color="bg-[#75a271]" /></div><button onClick={() => setLocation("/settings")} className="mt-7 flex items-center text-xs font-semibold text-primary transition hover:gap-2">KPIを調整する <ChevronRight className="ml-1 h-3.5 w-3.5" /></button></CardContent></Card>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[.85fr_1.15fr]">
      <Card className="soft-card rounded-2xl"><CardContent className="p-6"><p className="eyebrow">Content mix</p><h2 className="mt-1 text-lg font-bold">カテゴリ別の実績</h2>{categories.length ? <div className="mt-3 h-[210px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories} dataKey="impressions" nameKey="category" innerRadius={52} outerRadius={78} paddingAngle={4}>{categories.map((entry, index) => <Cell key={entry.category} fill={categoryColors[index % categoryColors.length]} />)}</Pie><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #e5e0d6", fontSize: 12 }} formatter={(value: number) => formatNumber(value)} /></PieChart></ResponsiveContainer></div> : <div className="mt-5"><EmptyState icon={BarChart3} title="まだ実績がありません" description="投稿後の数値を登録すると、カテゴリごとの反応を比較できます。" action={<Button size="sm" variant="outline" onClick={() => setLocation("/results")}>実績を記録</Button>} /></div>}</CardContent></Card>
      <Card className="soft-card rounded-2xl"><CardContent className="p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">Next moves</p><h2 className="mt-1 text-lg font-bold">次のアクション</h2></div><span className="mono text-[10px] text-muted-foreground">01 — 03</span></div><div className="mt-5 divide-y divide-border/70">{[{ icon: Lightbulb, title: "ネタを棚卸しする", body: "未使用のアイデアを選び、切り口を一つに絞ります。", path: "/ideas" }, { icon: Sparkles, title: "投稿案を比較する", body: "トーンと文字数を指定して、複数の表現を作成します。", path: "/drafts" }, { icon: LineChart, title: "実績からルールを更新する", body: "伸びた理由を、次回の生成条件に反映します。", path: "/analysis" }].map(item => <button key={item.title} onClick={() => setLocation(item.path)} className="group flex w-full gap-4 py-4 text-left first:pt-0"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-secondary text-primary"><item.icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{item.body}</p></div><ChevronRight className="mt-2 h-4 w-4 text-muted-foreground transition group-hover:translate-x-0.5 group-hover:text-primary" /></button>)}</div></CardContent></Card>
    </div>
  </div>;
}

function MetricCard({ label, value, detail, icon: Icon, accent }: { label: string; value: string; detail: string; icon: typeof TrendingUp; accent: string }) {
  const tones: Record<string, string> = { blue: "bg-[#e2edf6] text-[#49657e]", green: "bg-[#e6f0e3] text-[#658e62]", gold: "bg-[#f7edd8] text-[#b18138]", violet: "bg-[#efe9f2] text-[#8e6b97]" };
  return <Card className="soft-card rounded-2xl"><CardContent className="p-5"><div className="flex items-start justify-between"><p className="text-xs font-semibold text-muted-foreground">{label}</p><span className={cn("grid h-8 w-8 place-items-center rounded-xl", tones[accent])}><Icon className="h-4 w-4" /></span></div><p className="metric-number mt-5 text-[2.05rem] font-bold leading-none">{value}</p><p className="mt-3 text-[11px] text-muted-foreground">{detail}</p></CardContent></Card>;
}
function GoalProgress({ label, value, target, progress }: { label: string; value: string; target: string; progress: number; color: string }) { return <div><div className="flex justify-between gap-4 text-xs"><span className="font-semibold">{label}</span><span className="mono text-[10px] text-muted-foreground">{value} <span className="text-muted-foreground/60">/ {target}</span></span></div><Progress value={progress} className="mt-2 h-2 bg-secondary [&_[data-slot=progress-indicator]]:bg-primary" /><p className="mt-1.5 text-right text-[10px] text-muted-foreground">達成率 {Math.round(progress)}%</p></div>; }

function Ideas() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const ideas = trpc.growth.ideas.list.useQuery(undefined, { enabled: isAuthenticated });
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any | null>(null); const [form, setForm] = useState<IdeaForm>(blankIdea);
  const save = trpc.growth.ideas.create.useMutation({ onSuccess: () => { utils.growth.ideas.list.invalidate(); utils.growth.dashboard.invalidate(); toast.success("ネタを保存しました。"); setOpen(false); }, onError: e => toast.error(e.message) });
  const update = trpc.growth.ideas.update.useMutation({ onSuccess: () => { utils.growth.ideas.list.invalidate(); toast.success("ネタを更新しました。"); setOpen(false); }, onError: e => toast.error(e.message) });
  const remove = trpc.growth.ideas.delete.useMutation({ onSuccess: () => { utils.growth.ideas.list.invalidate(); utils.growth.dashboard.invalidate(); toast.success("ネタを削除しました。"); }, onError: e => toast.error(e.message) });
  const startCreate = () => { setEditing(null); setForm(blankIdea); setOpen(true); };
  const startEdit = (idea: any) => { setEditing(idea); setForm({ title: idea.title, summary: idea.summary ?? "", category: idea.category, tags: idea.tags.join(", "), sourceUrl: idea.sourceUrl ?? "", personalExperience: idea.personalExperience ?? "", targetUser: idea.targetUser ?? "", angle: idea.angle ?? "", priority: idea.priority, status: idea.status }); setOpen(true); };
  const submit = (e: React.FormEvent) => { e.preventDefault(); const payload = { ...form, tags: form.tags.split(",").map(tag => tag.trim()).filter(Boolean), summary: form.summary || null, sourceUrl: form.sourceUrl || null, personalExperience: form.personalExperience || null, targetUser: form.targetUser || null, angle: form.angle || null }; editing ? update.mutate({ id: editing.id, ...payload }) : save.mutate(payload); };
  const set = (key: keyof IdeaForm, value: string) => setForm(current => ({ ...current, [key]: value }));
  return <div className="container py-8 lg:py-11"><PageHeader eyebrow="Idea library / 02" title="発信の種を、逃さない。" description="気づき、経験、参考情報を投稿可能なネタとして残し、次の一手を選びやすくします。" action={<Button onClick={startCreate} className="rounded-xl bg-primary px-5 shadow-lg shadow-primary/15"><Plus className="mr-2 h-4 w-4" />ネタを登録</Button>} />
    <div className="mt-7 flex items-center gap-3 text-xs text-muted-foreground"><Badge variant="outline" className="rounded-full bg-card px-3 py-1">{ideas.data?.length ?? 0} 件のネタ</Badge><span>カテゴリ・タグ・ステータスで投稿準備を整理できます。</span></div>
    <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ideas.isLoading ? <LoadingCards count={6} /> : ideas.data?.length ? ideas.data.map(idea => <IdeaCard key={idea.id} idea={idea} onEdit={() => startEdit(idea)} onDelete={() => { if (window.confirm("このネタを削除しますか？")) remove.mutate({ id: idea.id }); }} />) : <div className="md:col-span-2 xl:col-span-3"><EmptyState icon={Lightbulb} title="投稿ネタはまだありません" description="日々の気づきや、届けたい経験を最初のネタとして登録しましょう。" action={<Button onClick={startCreate} size="sm"><Plus className="mr-2 h-4 w-4" />最初のネタを登録</Button>} /></div>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto rounded-2xl"><DialogHeader><p className="eyebrow">Idea editor</p><DialogTitle className="editorial-title text-2xl">{editing ? "ネタを磨く" : "新しいネタを残す"}</DialogTitle><DialogDescription>投稿の軸になる一次体験や切り口を、後から使える言葉で記録します。</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5 py-2"><div className="grid gap-5 sm:grid-cols-2"><Field label="ネタのタイトル *" className="sm:col-span-2"><Input required value={form.title} onChange={e => set("title", e.target.value)} placeholder="例：AIに業務を教える前に、まず観察する" /></Field><Field label="カテゴリ *"><Input required value={form.category} onChange={e => set("category", e.target.value)} /></Field><Field label="タグ（カンマ区切り）"><Input value={form.tags} onChange={e => set("tags", e.target.value)} placeholder="AI, 業務効率化" /></Field><Field label="概要" className="sm:col-span-2"><Textarea value={form.summary} onChange={e => set("summary", e.target.value)} rows={3} placeholder="このネタで伝えたい主張を短くまとめます。" /></Field><Field label="本人の経験" className="sm:col-span-2"><Textarea value={form.personalExperience} onChange={e => set("personalExperience", e.target.value)} rows={3} placeholder="実際に試したこと、失敗、変化など。" /></Field><Field label="切り口"><Input value={form.angle} onChange={e => set("angle", e.target.value)} placeholder="例：失敗から学んだこと" /></Field><Field label="想定読者"><Input value={form.targetUser} onChange={e => set("targetUser", e.target.value)} placeholder="例：非エンジニアの事務職" /></Field><Field label="参考URL"><Input value={form.sourceUrl} onChange={e => set("sourceUrl", e.target.value)} type="url" placeholder="https://" /></Field><Field label="優先度"><select value={form.priority} onChange={e => set("priority", e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></Field><Field label="ステータス"><select value={form.status} onChange={e => set("status", e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="unused">未使用</option><option value="drafting">投稿案作成中</option><option value="published">投稿済み</option><option value="archived">保管</option></select></Field></div><DialogFooter><Button type="button" variant="ghost" onClick={() => setOpen(false)}>キャンセル</Button><Button type="submit" disabled={save.isPending || update.isPending} className="rounded-xl"><Save className="mr-2 h-4 w-4" />{editing ? "更新する" : "保存する"}</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

function IdeaCard({ idea, onEdit, onDelete }: { idea: any; onEdit: () => void; onDelete: () => void }) {
  const state: Record<string, string> = { unused: "未使用", drafting: "投稿案作成中", published: "投稿済み", archived: "保管" };
  const priority: Record<string, string> = { high: "bg-[#f7e4df] text-[#a75847]", medium: "bg-[#f7edd8] text-[#ad7c30]", low: "bg-[#e7edf3] text-[#627b91]" };
  return <Card className="soft-card group rounded-2xl transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_16px_42px_-24px_rgba(20,36,57,.4)]"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><Badge className={cn("rounded-full border-0 px-2.5 py-1 text-[10px]", priority[idea.priority])}>{idea.priority === "high" ? "優先度 高" : idea.priority === "medium" ? "優先度 中" : "優先度 低"}</Badge><Badge variant="outline" className="rounded-full bg-card px-2.5 py-1 text-[10px]">{state[idea.status]}</Badge></div><div className="flex opacity-0 transition group-hover:opacity-100"><button onClick={onEdit} aria-label="ネタを編集" className="grid h-7 w-7 place-items-center rounded-lg text-muted-foreground hover:bg-secondary hover:text-primary"><Pencil className="h-3.5 w-3.5" /></button><button onClick={onDelete} aria-label="ネタを削除" className="grid h-7 w-7 place-items-center rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button></div></div><h3 className="mt-5 text-base font-bold leading-snug">{idea.title}</h3><p className="mt-2 line-clamp-2 min-h-10 text-xs leading-relaxed text-muted-foreground">{idea.summary || idea.personalExperience || "概要を追加すると、生成時の精度を高められます。"}</p><div className="mt-4 flex items-center justify-between border-t border-border/60 pt-4"><span className="text-[10px] font-semibold text-primary">{idea.category}</span><div className="flex max-w-[58%] gap-1 overflow-hidden">{idea.tags.slice(0, 3).map((tag: string) => <span key={tag} className="truncate rounded-md bg-secondary px-1.5 py-0.5 text-[9px] text-muted-foreground">#{tag}</span>)}</div></div></CardContent></Card>;
}

function Drafts() {
  const { isAuthenticated } = useAuth(); const utils = trpc.useUtils();
  const ideas = trpc.growth.ideas.list.useQuery(undefined, { enabled: isAuthenticated });
  const drafts = trpc.growth.drafts.list.useQuery(undefined, { enabled: isAuthenticated });
  const models = trpc.growth.models.useQuery(undefined, { enabled: isAuthenticated });
  const settings = trpc.growth.settings.get.useQuery(undefined, { enabled: isAuthenticated });
  const [open, setOpen] = useState(false); const [ideaId, setIdeaId] = useState(0); const [tone, setTone] = useState("知的で親しみやすい"); const [charLimit, setCharLimit] = useState(280); const [count, setCount] = useState(3); const [model, setModel] = useState("gpt-5-mini");
  const generate = trpc.growth.generate.useMutation({ onSuccess: result => { utils.growth.drafts.list.invalidate(); utils.growth.ideas.list.invalidate(); toast.success(`${result.createdCount}件の投稿案を生成しました。`); setOpen(false); }, onError: e => toast.error(e.message) });
  const update = trpc.growth.drafts.update.useMutation({ onSuccess: () => { utils.growth.drafts.list.invalidate(); toast.success("投稿案と品質評価を更新しました。"); }, onError: e => toast.error(e.message) });
  const remove = trpc.growth.drafts.delete.useMutation({ onSuccess: () => { utils.growth.drafts.list.invalidate(); toast.success("投稿案を削除しました。"); }, onError: e => toast.error(e.message) });
  const unusedIdeas = ideas.data?.filter(idea => idea.status !== "archived") ?? [];
  const start = () => { setIdeaId(unusedIdeas[0]?.id ?? 0); setTone(settings.data?.defaultTone ?? "知的で親しみやすい"); setModel(models.data?.some(m => m.id === "gpt-5-mini") ? "gpt-5-mini" : models.data?.[0]?.id ?? "gpt-5-mini"); setOpen(true); };
  return <div className="container py-8 lg:py-11"><PageHeader eyebrow="Writing studio / 03" title="あなたの経験を、届く言葉に。" description="ネタの背景、トーン、文字数を指定し、複数の投稿案を生成します。公開前には品質スコアと注意点を確認できます。" action={<Button onClick={start} disabled={!unusedIdeas.length} className="rounded-xl bg-primary px-5 shadow-lg shadow-primary/15"><WandSparkles className="mr-2 h-4 w-4" />投稿案を生成</Button>} />
    {!unusedIdeas.length && !ideas.isLoading && <div className="mt-6 rounded-2xl border border-[#e3d1a7] bg-[#fcf8ed] p-4 text-sm text-[#745b2a]"><CircleAlert className="mr-2 inline h-4 w-4" />先にネタを登録すると、AIが投稿の文脈を理解して投稿案を生成できます。</div>}
    <div className="mt-7 grid gap-5 xl:grid-cols-2">{drafts.isLoading ? <LoadingCards count={4} /> : drafts.data?.length ? drafts.data.map(draft => <DraftCard key={draft.id} draft={draft} onSave={(content, status) => update.mutate({ id: draft.id, content, tone: draft.tone, charLimit: draft.charLimit, status })} onDelete={() => { if (window.confirm("この投稿案を削除しますか？")) remove.mutate({ id: draft.id }); }} saving={update.isPending} />) : <div className="xl:col-span-2"><EmptyState icon={Sparkles} title="まだ投稿案はありません" description="ネタを一つ選び、書きたい温度感を指定して最初の投稿案を作成しましょう。" action={unusedIdeas.length ? <Button onClick={start} size="sm"><WandSparkles className="mr-2 h-4 w-4" />投稿案を生成</Button> : <Button size="sm" variant="outline" onClick={() => location.assign("/ideas")}>ネタを登録</Button>} /></div>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-xl rounded-2xl"><DialogHeader><p className="eyebrow">Generation brief</p><DialogTitle className="editorial-title text-2xl">投稿案を設計する</DialogTitle><DialogDescription>AIは編集者です。あなたのネタと経験が、投稿の中心に残るように設計します。</DialogDescription></DialogHeader><div className="grid gap-5 py-3 sm:grid-cols-2"><Field label="ベースにするネタ *" className="sm:col-span-2"><select value={ideaId} onChange={e => setIdeaId(Number(e.target.value))} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{unusedIdeas.map(idea => <option key={idea.id} value={idea.id}>{idea.title}</option>)}</select></Field><Field label="トーン"><Input value={tone} onChange={e => setTone(e.target.value)} placeholder="例：親しみやすく、端的" /></Field><Field label="上限文字数"><Input type="number" min={50} max={1000} value={charLimit} onChange={e => setCharLimit(Number(e.target.value))} /></Field><Field label="生成数"><select value={count} onChange={e => setCount(Number(e.target.value))} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n}案</option>)}</select></Field><Field label="AIモデル"><select value={model} onChange={e => setModel(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{(models.data?.length ? models.data : [{ id: "gpt-5-mini" }]).map(m => <option key={m.id} value={m.id}>{m.id}</option>)}</select></Field></div><DialogFooter><Button variant="ghost" onClick={() => setOpen(false)}>キャンセル</Button><Button onClick={() => generate.mutate({ ideaId, tone, charLimit, count, model })} disabled={!ideaId || generate.isPending} className="rounded-xl">{generate.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <WandSparkles className="mr-2 h-4 w-4" />}生成する</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function DraftCard({ draft, onSave, onDelete, saving }: { draft: any; onSave: (content: string, status: "generated" | "selected" | "published" | "discarded") => void; onDelete: () => void; saving: boolean }) {
  const [content, setContent] = useState(draft.content); const [copied, setCopied] = useState(false);
  const qualityTone = draft.qualityScore >= 80 ? "text-[#558151] bg-[#e6f0e3]" : draft.qualityScore >= 60 ? "text-[#a57528] bg-[#f7edd8]" : "text-[#a75847] bg-[#f7e4df]";
  const copy = async () => { await navigator.clipboard.writeText(content); setCopied(true); toast.success("投稿案をコピーしました。"); window.setTimeout(() => setCopied(false), 1800); };
  return <Card className="soft-card overflow-hidden rounded-2xl"><CardContent className="p-0"><div className="flex items-start justify-between border-b border-border/70 px-5 py-4"><div><p className="eyebrow">Generated draft</p><div className="mt-1.5 flex flex-wrap items-center gap-2"><Badge className={cn("rounded-full border-0 px-2.5 py-1 text-[10px]", qualityTone)}>品質 {draft.qualityScore}/100</Badge><span className="mono text-[10px] text-muted-foreground">{draft.charCount} / {draft.charLimit} chars</span></div></div><div className="flex gap-1"><button onClick={copy} aria-label="コピー" className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-secondary hover:text-primary">{copied ? <Check className="h-4 w-4 text-[#558151]" /> : <Copy className="h-4 w-4" />}</button><button onClick={onDelete} aria-label="削除" className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="h-4 w-4" /></button></div></div><div className="p-5"><Textarea value={content} onChange={e => setContent(e.target.value)} rows={7} className="resize-none border-0 bg-transparent px-0 text-sm leading-7 shadow-none focus-visible:ring-0" /><div className="mt-4 rounded-xl bg-secondary/70 p-3"><div className="flex items-center gap-2"><CircleCheck className="h-4 w-4 text-[#658e62]" /><span className="text-xs font-semibold">自動品質チェック</span><span className="ml-auto text-[10px] text-muted-foreground">可読性 {draft.readabilityScore}/100</span></div>{draft.warnings.length ? <ul className="mt-2 space-y-1 text-[11px] leading-relaxed text-muted-foreground">{draft.warnings.map((warning: string) => <li key={warning}>・{warning}</li>)}</ul> : <p className="mt-2 text-[11px] text-muted-foreground">文字数・禁止ワード・文の長さを確認済みです。</p>}</div><div className="mt-4 flex flex-wrap gap-2"><Button variant={draft.status === "selected" ? "default" : "outline"} size="sm" onClick={() => onSave(content, "selected")} disabled={saving} className="rounded-lg">{saving ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Check className="mr-1.5 h-3.5 w-3.5" />}採用する</Button><Button variant="ghost" size="sm" onClick={() => onSave(content, "generated")} disabled={saving} className="rounded-lg text-muted-foreground"><Save className="mr-1.5 h-3.5 w-3.5" />品質を再評価</Button></div></div></CardContent></Card>;
}

function Results() {
  const { isAuthenticated } = useAuth(); const utils = trpc.useUtils();
  const results = trpc.growth.results.list.useQuery(undefined, { enabled: isAuthenticated }); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any | null>(null); const [form, setForm] = useState<ResultForm>(blankResult());
  const create = trpc.growth.results.create.useMutation({ onSuccess: () => { utils.growth.results.list.invalidate(); utils.growth.dashboard.invalidate(); toast.success("投稿実績を記録しました。"); setOpen(false); }, onError: e => toast.error(e.message) });
  const update = trpc.growth.results.update.useMutation({ onSuccess: () => { utils.growth.results.list.invalidate(); utils.growth.dashboard.invalidate(); toast.success("投稿実績を更新しました。"); setOpen(false); }, onError: e => toast.error(e.message) });
  const remove = trpc.growth.results.delete.useMutation({ onSuccess: () => { utils.growth.results.list.invalidate(); utils.growth.dashboard.invalidate(); toast.success("投稿実績を削除しました。"); }, onError: e => toast.error(e.message) });
  const startCreate = () => { setEditing(null); setForm(blankResult()); setOpen(true); };
  const startEdit = (row: any) => { setEditing(row); setForm({ title: row.title, category: row.category, postUrl: row.postUrl ?? "", postedAt: new Date(row.postedAt).toISOString().slice(0, 16), impressions: row.impressions, engagements: row.engagements, likes: row.likes, replies: row.replies, reposts: row.reposts, bookmarks: row.bookmarks, clicks: row.clicks, notes: row.notes ?? "" }); setOpen(true); };
  const set = (key: keyof ResultForm, value: string | number) => setForm(current => ({ ...current, [key]: value }));
  const submit = (e: React.FormEvent) => { e.preventDefault(); const data = { ...form, postedAt: new Date(form.postedAt), postUrl: form.postUrl || null, notes: form.notes || null }; editing ? update.mutate({ id: editing.id, ...data }) : create.mutate(data); };
  return <div className="container py-8 lg:py-11"><PageHeader eyebrow="Performance log / 04" title="反応を、正確に残す。" description="投稿URLと数値を記録し、感覚ではなく実績をもとに次の発信を改善します。" action={<Button onClick={startCreate} className="rounded-xl bg-primary px-5 shadow-lg shadow-primary/15"><Plus className="mr-2 h-4 w-4" />実績を記録</Button>} />
    <Card className="soft-card mt-7 overflow-hidden rounded-2xl"><CardContent className="p-0">{results.isLoading ? <div className="p-6"><LoadingCards count={4} /></div> : results.data?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead className="border-b border-border/70 bg-secondary/45"><tr className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground"><th className="px-6 py-4">投稿</th><th className="px-4 py-4">公開日</th><th className="px-4 py-4 text-right">Impressions</th><th className="px-4 py-4 text-right">Engagements</th><th className="px-4 py-4 text-right">ER</th><th className="px-6 py-4"></th></tr></thead><tbody>{results.data.map(row => { const er = row.impressions ? row.engagements / row.impressions * 100 : 0; return <tr key={row.id} className="border-b border-border/50 last:border-0 hover:bg-secondary/20"><td className="px-6 py-4"><p className="max-w-[270px] truncate text-sm font-semibold">{row.title}</p><p className="mt-1 text-[10px] text-primary">{row.category}</p></td><td className="px-4 py-4 text-xs text-muted-foreground">{formatDate(row.postedAt)}</td><td className="px-4 py-4 text-right text-sm font-semibold">{formatNumber(row.impressions)}</td><td className="px-4 py-4 text-right text-sm font-semibold">{formatNumber(row.engagements)}</td><td className="px-4 py-4 text-right"><Badge className="rounded-full border-0 bg-[#e6f0e3] px-2.5 py-1 text-[10px] text-[#558151]">{rate(er)}</Badge></td><td className="px-6 py-4"><div className="flex justify-end gap-1"><button onClick={() => startEdit(row)} className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-secondary hover:text-primary"><Pencil className="h-3.5 w-3.5" /></button><button onClick={() => { if (window.confirm("この実績を削除しますか？")) remove.mutate({ id: row.id }); }} className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button></div></td></tr>; })}</tbody></table></div> : <EmptyState icon={ClipboardPenLine} title="投稿実績はまだありません" description="Xに手動投稿した後、表示数や反応を記録しましょう。分析画面で傾向を確認できます。" action={<Button onClick={startCreate} size="sm"><Plus className="mr-2 h-4 w-4" />実績を記録</Button>} />}</CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] max-w-2xl overflow-y-auto rounded-2xl"><DialogHeader><p className="eyebrow">Performance record</p><DialogTitle className="editorial-title text-2xl">{editing ? "実績を更新する" : "投稿実績を記録する"}</DialogTitle><DialogDescription>実際に確認できる数値を入力してください。エンゲージメント率は自動計算されます。</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5 py-2"><div className="grid gap-5 sm:grid-cols-2"><Field label="投稿タイトル *" className="sm:col-span-2"><Input required value={form.title} onChange={e => set("title", e.target.value)} placeholder="記録用のタイトルを入力" /></Field><Field label="カテゴリ *"><Input required value={form.category} onChange={e => set("category", e.target.value)} /></Field><Field label="投稿日時 *"><Input required type="datetime-local" value={form.postedAt} onChange={e => set("postedAt", e.target.value)} /></Field><Field label="投稿URL"><Input type="url" value={form.postUrl} onChange={e => set("postUrl", e.target.value)} placeholder="https://x.com/..." /></Field><Field label="インプレッション *"><Input required type="number" min="0" value={form.impressions} onChange={e => set("impressions", Number(e.target.value))} /></Field><Field label="エンゲージメント *"><Input required type="number" min="0" value={form.engagements} onChange={e => set("engagements", Number(e.target.value))} /></Field><Field label="いいね"><Input type="number" min="0" value={form.likes} onChange={e => set("likes", Number(e.target.value))} /></Field><Field label="返信"><Input type="number" min="0" value={form.replies} onChange={e => set("replies", Number(e.target.value))} /></Field><Field label="リポスト"><Input type="number" min="0" value={form.reposts} onChange={e => set("reposts", Number(e.target.value))} /></Field><Field label="ブックマーク"><Input type="number" min="0" value={form.bookmarks} onChange={e => set("bookmarks", Number(e.target.value))} /></Field><Field label="リンククリック"><Input type="number" min="0" value={form.clicks} onChange={e => set("clicks", Number(e.target.value))} /></Field><Field label="メモ" className="sm:col-span-2"><Textarea value={form.notes} onChange={e => set("notes", e.target.value)} rows={3} placeholder="投稿時の状況や、気づいた反応を記録します。" /></Field></div><DialogFooter><Button type="button" variant="ghost" onClick={() => setOpen(false)}>キャンセル</Button><Button type="submit" disabled={create.isPending || update.isPending} className="rounded-xl"><Save className="mr-2 h-4 w-4" />記録する</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

function Analysis() {
  const { isAuthenticated } = useAuth(); const utils = trpc.useUtils(); const dashboard = trpc.growth.dashboard.useQuery(undefined, { enabled: isAuthenticated }); const settings = trpc.growth.settings.get.useQuery(undefined, { enabled: isAuthenticated }); const weeklyReports = trpc.weeklyReports.list.useQuery(undefined, { enabled: isAuthenticated }); const summary = dashboard.data?.summary; const categories = dashboard.data?.categoryBreakdown ?? []; const trend = dashboard.data?.trend ?? [];
  const generateWeekly = trpc.weeklyReports.generate.useMutation({ onSuccess: result => { utils.weeklyReports.list.invalidate(); toast.success(result.created ? "週次レポートを生成しました。" : "週次レポートを再生成しました。"); }, onError: error => toast.error(error.message) });
  const activateSchedule = trpc.weeklyReports.schedule.useMutation({ onSuccess: () => { utils.growth.settings.get.invalidate(); toast.success("週次レポートの自動生成を有効化しました。"); }, onError: error => toast.error(error.message) });
  const latestReport = weeklyReports.data?.[0];
  const best = useMemo(() => [...categories].sort((a, b) => b.engagementRate - a.engagementRate)[0], [categories]);
  return <div className="container py-8 lg:py-11"><PageHeader eyebrow="Insights desk / 05" title="数字の奥に、次の仮説を。" description="記録した投稿実績から、到達・反応・カテゴリの傾向を読み解きます。実績が増えるほど、改善の精度が上がります。" action={<Button onClick={() => generateWeekly.mutate()} disabled={generateWeekly.isPending} className="rounded-xl bg-primary px-5 shadow-lg shadow-primary/15">{generateWeekly.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <WandSparkles className="mr-2 h-4 w-4" />}{latestReport ? "週次レポートを再生成" : "週次レポートを生成"}</Button>} />
    <WeeklyReportPanel report={latestReport} autoEnabled={Boolean(settings.data?.weeklyReportEnabled && settings.data?.weeklyReportCronTaskUid)} generating={generateWeekly.isPending} activating={activateSchedule.isPending} onGenerate={() => generateWeekly.mutate()} onActivate={() => activateSchedule.mutate({ enabled: true })} />
    <div className="mt-7 grid gap-4 md:grid-cols-3"><Insight label="平均インプレッション" value={summary?.postCount ? formatNumber(Math.round((summary.impressions ?? 0) / summary.postCount)) : "—"} note="投稿あたりの到達" /><Insight label="平均エンゲージメント" value={summary?.postCount ? formatNumber(Math.round((summary.engagements ?? 0) / summary.postCount)) : "—"} note="投稿あたりの反応" /><Insight label="最も反応が高いカテゴリ" value={best?.category ?? "—"} note={best ? `ER ${rate(best.engagementRate)}` : "実績データ待ち"} /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.95fr]"><Card className="soft-card rounded-2xl"><CardContent className="p-6"><p className="eyebrow">Reach & response</p><h2 className="mt-1 text-lg font-bold">インプレッションと反応の推移</h2><div className="mt-6 h-[290px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend} margin={{ left: -18, right: 8 }}><CartesianGrid vertical={false} stroke="#e5e0d6" strokeDasharray="4 4" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#718096" }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#718096" }} /><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #e5e0d6", fontSize: 12 }} /><Bar dataKey="impressions" name="インプレッション" fill="#49657e" radius={[6, 6, 0, 0]} /><Bar dataKey="engagements" name="エンゲージメント" fill="#d6aa55" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></CardContent></Card><Card className="soft-card rounded-2xl"><CardContent className="p-6"><p className="eyebrow">Reading the signal</p><h2 className="mt-1 text-lg font-bold">今回の示唆</h2>{summary?.postCount ? <div className="mt-6 space-y-4"><AnalysisNote icon={TrendingUp} title={summary.engagementRate >= summary.engagementRateTarget ? "エンゲージメント目標を達成中" : "エンゲージメントを伸ばす余地あり"} body={summary.engagementRate >= summary.engagementRateTarget ? "設定した目標を上回っています。上位カテゴリや投稿の構成を、次回の生成ルールに言語化しましょう。" : "投稿の冒頭に具体的な状況や問いを置き、読み手が自分事化しやすい構成を試してみましょう。"} /><AnalysisNote icon={BookOpenText} title={best ? `${best.category} が最も高反応` : "カテゴリ比較の準備中"} body={best ? `現在の記録では、エンゲージメント率 ${rate(best.engagementRate)} で最も反応が高いカテゴリです。連続投稿で再現性を確かめましょう。` : "複数のカテゴリで実績を残すと、テーマ別の比較が可能になります。"} /></div> : <div className="mt-6"><EmptyState icon={BarChart3} title="分析する実績がありません" description="まずは投稿実績を記録すると、ここに実データの傾向と改善の示唆が表示されます。" /></div>}</CardContent></Card></div>
    <Card className="soft-card mt-6 rounded-2xl"><CardContent className="p-6"><div className="flex items-end justify-between"><div><p className="eyebrow">By category</p><h2 className="mt-1 text-lg font-bold">カテゴリ別パフォーマンス</h2></div><span className="mono text-[10px] text-muted-foreground">{categories.length} categories</span></div>{categories.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="pb-3">カテゴリ</th><th className="pb-3 text-right">投稿数</th><th className="pb-3 text-right">インプレッション</th><th className="pb-3 text-right">エンゲージメント</th><th className="pb-3 text-right">ER</th></tr></thead><tbody>{categories.map((category, index) => <tr key={category.category} className="border-t border-border/60"><td className="py-4"><span className="mr-2 inline-block h-2 w-2 rounded-full" style={{ background: categoryColors[index % categoryColors.length] }} /> <span className="text-sm font-semibold">{category.category}</span></td><td className="py-4 text-right text-sm">{category.posts}</td><td className="py-4 text-right text-sm">{formatNumber(category.impressions)}</td><td className="py-4 text-right text-sm">{formatNumber(category.engagements)}</td><td className="py-4 text-right text-sm font-semibold text-primary">{rate(category.engagementRate)}</td></tr>)}</tbody></table></div> : <p className="mt-5 text-sm text-muted-foreground">実績を記録するとカテゴリ別の比較が表示されます。</p>}</CardContent></Card>
  </div>;
}

function Insight({ label, value, note }: { label: string; value: string; note: string }) { return <Card className="soft-card rounded-2xl"><CardContent className="p-5"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="metric-number mt-4 truncate text-2xl font-bold">{value}</p><p className="mt-2 text-[11px] text-muted-foreground">{note}</p></CardContent></Card>; }
function AnalysisNote({ icon: Icon, title, body }: { icon: typeof TrendingUp; title: string; body: string }) { return <div className="rounded-xl border border-border/70 bg-secondary/40 p-4"><Icon className="h-4 w-4 text-primary" /><p className="mt-2 text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{body}</p></div>; }

function Settings() {
  const { isAuthenticated } = useAuth(); const utils = trpc.useUtils(); const settings = trpc.growth.settings.get.useQuery(undefined, { enabled: isAuthenticated }); const exporter = trpc.growth.exportData.useQuery(undefined, { enabled: false });
  const [form, setForm] = useState({ impressionsTarget: 1000, engagementRate: 3, postsPerWeekTarget: 3, bannedWords: "", analysisRules: "", defaultTone: "知的で親しみやすい" });
  const [loaded, setLoaded] = useState(false);
  useEffect(() => {
    if (!settings.data || loaded) return;
    setForm({ impressionsTarget: settings.data.impressionsTarget, engagementRate: settings.data.engagementRateTargetBps / 100, postsPerWeekTarget: settings.data.postsPerWeekTarget, bannedWords: settings.data.bannedWords.join(", "), analysisRules: settings.data.analysisRules ?? "", defaultTone: settings.data.defaultTone });
    setLoaded(true);
  }, [loaded, settings.data]);
  const save = trpc.growth.settings.save.useMutation({ onSuccess: () => { utils.growth.settings.get.invalidate(); utils.growth.dashboard.invalidate(); toast.success("運用ルールとKPIを保存しました。"); }, onError: e => toast.error(e.message) });
  const doExport = async (kind: "json" | "ideas" | "results") => { const response = await exporter.refetch(); const data = response.data; if (!data) { toast.error("エクスポート用データを取得できませんでした。"); return; } if (kind === "json") { download("sns-growth-copilot-export.json", JSON.stringify(data, null, 2), "application/json"); } else { const rows = kind === "ideas" ? data.ideas : data.results; const headers = rows[0] ? Object.keys(rows[0]) : []; const csv = [headers.join(","), ...rows.map(row => headers.map(key => csvCell((row as any)[key])).join(","))].join("\n"); download(`sns-growth-copilot-${kind}.csv`, `\uFEFF${csv}`, "text/csv;charset=utf-8"); } toast.success("データをエクスポートしました。"); };
  return <div className="container py-8 lg:py-11"><PageHeader eyebrow="System settings / 06" title="自分の基準を、仕組みにする。" description="目標値と投稿ルールを更新すると、分析指標と投稿案の品質チェックに反映されます。" />
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><Card className="soft-card rounded-2xl"><CardContent className="p-6"><p className="eyebrow">KPI & rules</p><h2 className="mt-1 text-lg font-bold">運用の基準</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="目標インプレッション"><Input type="number" min="1" value={form.impressionsTarget} onChange={e => setForm({ ...form, impressionsTarget: Number(e.target.value) })} /></Field><Field label="目標エンゲージメント率（%）"><Input type="number" min="0.01" step="0.01" value={form.engagementRate} onChange={e => setForm({ ...form, engagementRate: Number(e.target.value) })} /></Field><Field label="週あたりの投稿目標"><Input type="number" min="1" value={form.postsPerWeekTarget} onChange={e => setForm({ ...form, postsPerWeekTarget: Number(e.target.value) })} /></Field><Field label="既定のトーン"><Input value={form.defaultTone} onChange={e => setForm({ ...form, defaultTone: e.target.value })} /></Field><Field label="禁止ワード（カンマ区切り）" className="sm:col-span-2"><Input value={form.bannedWords} onChange={e => setForm({ ...form, bannedWords: e.target.value })} placeholder="例：絶対, 必ず儲かる" /></Field><Field label="分析・生成ルール" className="sm:col-span-2"><Textarea value={form.analysisRules} onChange={e => setForm({ ...form, analysisRules: e.target.value })} rows={5} placeholder="例：一次体験を必ず入れる。専門用語は簡潔に説明する。" /></Field></div><Button onClick={() => save.mutate({ impressionsTarget: form.impressionsTarget, engagementRateTargetBps: Math.round(form.engagementRate * 100), postsPerWeekTarget: form.postsPerWeekTarget, bannedWords: form.bannedWords.split(",").map(word => word.trim()).filter(Boolean), analysisRules: form.analysisRules, defaultTone: form.defaultTone })} disabled={save.isPending || !loaded} className="mt-7 rounded-xl"><Save className="mr-2 h-4 w-4" />{save.isPending ? "保存中…" : "運用基準を保存"}</Button></CardContent></Card>
      <div className="space-y-6"><Card className="soft-card rounded-2xl"><CardContent className="p-6"><p className="eyebrow">Data portability</p><h2 className="mt-1 text-lg font-bold">データを持ち出す</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">記録したネタ・投稿案・実績・設定を、いつでも標準形式で保存できます。</p><div className="mt-5 space-y-2"><Button onClick={() => doExport("ideas")} variant="outline" className="w-full justify-start rounded-xl bg-card"><FileSpreadsheet className="mr-2 h-4 w-4 text-[#658e62]" />ネタをCSVで出力 <ArrowDownToLine className="ml-auto h-4 w-4 text-muted-foreground" /></Button><Button onClick={() => doExport("results")} variant="outline" className="w-full justify-start rounded-xl bg-card"><FileSpreadsheet className="mr-2 h-4 w-4 text-[#49657e]" />実績をCSVで出力 <ArrowDownToLine className="ml-auto h-4 w-4 text-muted-foreground" /></Button><Button onClick={() => doExport("json")} variant="outline" className="w-full justify-start rounded-xl bg-card"><FileJson2 className="mr-2 h-4 w-4 text-[#8e6b97]" />すべてをJSONで出力 <ArrowDownToLine className="ml-auto h-4 w-4 text-muted-foreground" /></Button></div></CardContent></Card><Card className="rounded-2xl border-0 bg-primary text-primary-foreground shadow-lg shadow-primary/10"><CardContent className="p-6"><Settings2 className="h-5 w-5 text-[oklch(0.76_0.12_75)]" /><h3 className="mt-5 text-sm font-bold">自分の言葉を中心に。</h3><p className="mt-2 text-xs leading-relaxed text-primary-foreground/70">AIは投稿活動を代替するのではなく、あなたの経験・判断・学びを整理し、改善するために使います。</p></CardContent></Card></div></div>
  </div>;
}

function Field({ label, children, className }: { label: string; children: React.ReactNode; className?: string }) { return <div className={className}><Label className="mb-2 block text-xs font-semibold text-foreground/80">{label}</Label>{children}</div>; }
function LoadingCards({ count }: { count: number }) { return <>{Array.from({ length: count }).map((_, index) => <div key={index} className="h-44 animate-pulse rounded-2xl border border-border bg-card/60" />)}</>; }

export default function GrowthCopilot() {
  const [location] = useLocation();
  return <AuthGate>{location === "/ideas" ? <Ideas /> : location === "/drafts" ? <Drafts /> : location === "/results" ? <Results /> : location === "/analysis" ? <Analysis /> : location === "/settings" ? <Settings /> : <Overview />}</AuthGate>;
}
function WeeklyReportPanel({ report, autoEnabled, generating, activating, onGenerate, onActivate }: { report: any; autoEnabled: boolean; generating: boolean; activating: boolean; onGenerate: () => void; onActivate: () => void }) {
  const rangeEnd = report ? new Date(new Date(report.weekEnd).getTime() - 24 * 60 * 60 * 1000) : null;
  return <Card className="soft-card mt-6 overflow-hidden rounded-2xl"><CardContent className="p-0">
    <div className="flex flex-col gap-4 border-b border-border/70 bg-[linear-gradient(120deg,#eef3f6,transparent_60%,#fbf2df)] px-6 py-5 sm:flex-row sm:items-center sm:justify-between">
      <div><p className="eyebrow">Weekly intelligence</p><h2 className="mt-1 text-xl font-bold">週次分析レポート</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground">毎週月曜日 09:00（日本時間）に、前週（月曜〜日曜）の実績を集計します。</p></div>
      <div className="flex items-center gap-2"><Badge className={cn("rounded-full border-0 px-3 py-1 text-[10px]", autoEnabled ? "bg-[#e6f0e3] text-[#558151]" : "bg-[#f7edd8] text-[#a57528]")}>{autoEnabled ? "自動生成 有効" : "自動生成 未有効化"}</Badge>{!autoEnabled && <Button variant="outline" size="sm" onClick={onActivate} disabled={activating} className="rounded-lg bg-card">{activating ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Sparkles className="mr-1.5 h-3.5 w-3.5" />}自動生成を有効化</Button>}</div>
    </div>
    {report ? <div className="p-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="mono text-[10px] uppercase tracking-wider text-muted-foreground">{formatDate(report.weekStart)} — {rangeEnd && formatDate(rangeEnd)} / {report.source === "scheduled" ? "Scheduled" : "Manual"}</p><h3 className="editorial-title mt-2 text-2xl font-bold leading-snug">{report.insights.headline}</h3><p className="mt-2 max-w-3xl text-sm leading-7 text-muted-foreground">{report.insights.summary}</p></div><div className="grid grid-cols-3 gap-2 sm:min-w-[250px]"><ReportMetric label="投稿" value={`${report.postCount}`} /><ReportMetric label="表示" value={formatNumber(report.impressions)} /><ReportMetric label="ER" value={rate(report.engagementRateBps / 100)} /></div></div>
      <div className="mt-6 grid gap-4 lg:grid-cols-3"><ReportList title="良かった点" items={report.insights.wins} tone="green" /><ReportList title="確認したい点" items={report.insights.risks} tone="gold" /><ReportList title="次週のアクション" items={report.insights.actions} tone="blue" /></div>
      {report.categoryBreakdown.length ? <div className="mt-6 border-t border-border/70 pt-5"><p className="eyebrow">Category signal</p><div className="mt-3 flex flex-wrap gap-2">{report.categoryBreakdown.map((category: any) => <span key={category.category} className="rounded-full border border-border bg-secondary/60 px-3 py-1.5 text-[11px]"><strong>{category.category}</strong><span className="ml-2 text-muted-foreground">{category.posts}件 / ER {rate(category.engagementRate)}</span></span>)}</div></div> : null}
    </div> : <EmptyState icon={WandSparkles} title="最初の週次レポートを作りましょう" description="投稿実績を記録したら、前週のKPI・傾向・次週のアクションを一つのレポートにまとめられます。" action={<Button onClick={onGenerate} disabled={generating} size="sm"><WandSparkles className="mr-2 h-4 w-4" />週次レポートを生成</Button>} />}
  </CardContent></Card>;
}
function ReportMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border/70 bg-card/70 px-3 py-2 text-center"><p className="mono text-[9px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
function ReportList({ title, items, tone }: { title: string; items: string[]; tone: "green" | "gold" | "blue" }) { const tones = { green: "border-[#cfe1ca] bg-[#f2f8f0]", gold: "border-[#ecd8ae] bg-[#fcf8ed]", blue: "border-[#cddbe6] bg-[#f3f7fa]" }; return <div className={cn("rounded-xl border p-4", tones[tone])}><p className="text-xs font-bold">{title}</p><ul className="mt-3 space-y-2 text-[11px] leading-relaxed text-muted-foreground">{items.map(item => <li key={item}>・{item}</li>)}</ul></div>; }
