import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { ArrowRight, BarChart3, BookOpenText, Loader2, TrendingUp, WandSparkles } from "lucide-react";
import { useMemo } from "react";
import { Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { useLocation } from "wouter";

const categoryColors = ["#49657e", "#a8c4a2", "#d6aa55", "#b799b3", "#d98d68"];

function formatNumber(value: number) { return new Intl.NumberFormat("ja-JP", { notation: value >= 10000 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value); }
function formatDate(value: Date | string) { return new Intl.DateTimeFormat("ja-JP", { month: "short", day: "numeric" }).format(new Date(value)); }
function rate(value: number) { return `${value.toFixed(2)}%`; }

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="flex flex-col gap-5 border-b border-border/70 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="editorial-title mt-2 text-3xl font-bold text-foreground sm:text-[2.3rem]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{description}</p></div>{action && <div className="shrink-0">{action}</div>}</div>;
}

function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) {
  return <div className="flex min-h-[250px] flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card/55 px-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-secondary text-primary"><BarChart3 className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm leading-relaxed text-muted-foreground">{description}</p>{action ? <div className="mt-4">{action}</div> : null}</div>;
}

export function GrowthAnalysis() {
  const { isAuthenticated } = useAuth(); const utils = trpc.useUtils(); const dashboard = trpc.growth.dashboard.useQuery(undefined, { enabled: isAuthenticated }); const weeklyReports = trpc.weeklyReports.list.useQuery(undefined, { enabled: isAuthenticated }); const weeklyRuns = trpc.weeklyReports.runs.useQuery(undefined, { enabled: isAuthenticated }); const summary = dashboard.data?.summary; const categories = dashboard.data?.categoryBreakdown ?? []; const trend = dashboard.data?.trend ?? [];
  const refreshWeekly = () => { utils.weeklyReports.list.invalidate(); utils.weeklyReports.runs.invalidate(); };
  const generateWeekly = trpc.weeklyReports.generate.useMutation({ onSuccess: result => { refreshWeekly(); toast.success(result.created ? "週次レポートを生成しました。" : "週次レポートを再生成しました。"); }, onError: error => toast.error(error.message) });
  const retryWeekly = trpc.weeklyReports.retry.useMutation({ onSuccess: () => { refreshWeekly(); toast.success("週次レポートを再試行しました。"); }, onError: error => toast.error(error.message) });
  const latestReport = weeklyReports.data?.[0];
  const best = useMemo(() => [...categories].sort((a, b) => b.engagementRate - a.engagementRate)[0], [categories]);
  return <div className="container py-8 lg:py-11"><PageHeader eyebrow="Insights desk / 05" title="数字の奥に、次の仮説を。" description="記録した投稿実績から、到達・反応・カテゴリの傾向を読み解きます。実績が増えるほど、改善の精度が上がります。" action={<Button onClick={() => generateWeekly.mutate()} disabled={generateWeekly.isPending} className="rounded-xl bg-primary px-5 shadow-lg shadow-primary/15">{generateWeekly.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <WandSparkles className="mr-2 h-4 w-4" />}{latestReport ? "週次レポートを再生成" : "週次レポートを生成"}</Button>} />
    <WeeklyReportPanel report={latestReport} generating={generateWeekly.isPending} onGenerate={() => generateWeekly.mutate()} />
    <WeeklyRunHistory runs={weeklyRuns.data ?? []} retrying={retryWeekly.isPending} onRetry={() => retryWeekly.mutate()} />
    <div className="mt-7 grid gap-4 md:grid-cols-3"><Insight label="平均インプレッション" value={summary?.postCount ? formatNumber(Math.round((summary.impressions ?? 0) / summary.postCount)) : "—"} note="投稿あたりの到達" /><Insight label="平均エンゲージメント" value={summary?.postCount ? formatNumber(Math.round((summary.engagements ?? 0) / summary.postCount)) : "—"} note="投稿あたりの反応" /><Insight label="最も反応が高いカテゴリ" value={best?.category ?? "—"} note={best ? `ER ${rate(best.engagementRate)}` : "実績データ待ち"} /></div>
    <ComparisonStrip summary={summary} report={latestReport} />
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.95fr]"><Card className="soft-card rounded-2xl"><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Reach & response</p><h2 className="mt-1 text-lg font-bold">インプレッションと反応の推移</h2></div>{latestReport?.postCount ? <Badge variant="outline" className="rounded-full bg-card px-2.5 py-1 text-[10px]">破線：前週の投稿あたり平均</Badge> : null}</div><div className="mt-6 h-[290px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={trend} margin={{ left: -18, right: 8 }}><CartesianGrid vertical={false} stroke="#e5e0d6" strokeDasharray="4 4" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#718096" }} /><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#718096" }} /><Tooltip contentStyle={{ borderRadius: 14, border: "1px solid #e5e0d6", fontSize: 12 }} />{latestReport?.postCount ? <ReferenceLine y={Math.round(latestReport.impressions / latestReport.postCount)} stroke="#b18138" strokeDasharray="5 5" label={{ value: "前週平均", fill: "#9a7333", fontSize: 10, position: "insideTopRight" }} /> : null}<Bar dataKey="impressions" name="インプレッション" fill="#49657e" radius={[6, 6, 0, 0]} /><Bar dataKey="engagements" name="エンゲージメント" fill="#d6aa55" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></CardContent></Card><Card className="soft-card rounded-2xl"><CardContent className="p-6"><p className="eyebrow">Reading the signal</p><h2 className="mt-1 text-lg font-bold">今回の示唆</h2>{summary?.postCount ? <div className="mt-6 space-y-4"><AnalysisNote icon={TrendingUp} title={summary.engagementRate >= summary.engagementRateTarget ? "エンゲージメント目標を達成中" : "エンゲージメントを伸ばす余地あり"} body={summary.engagementRate >= summary.engagementRateTarget ? "設定した目標を上回っています。上位カテゴリや投稿の構成を、次回の生成ルールに言語化しましょう。" : "投稿の冒頭に具体的な状況や問いを置き、読み手が自分事化しやすい構成を試してみましょう。"} /><AnalysisNote icon={BookOpenText} title={best ? `${best.category} が最も高反応` : "カテゴリ比較の準備中"} body={best ? `現在の記録では、エンゲージメント率 ${rate(best.engagementRate)} で最も反応が高いカテゴリです。連続投稿で再現性を確かめましょう。` : "複数のカテゴリで実績を残すと、テーマ別の比較が可能になります。"} /></div> : <div className="mt-6"><EmptyState title="分析する実績がありません" description="まずは投稿実績を記録すると、ここに実データの傾向と改善の示唆が表示されます。" /></div>}</CardContent></Card></div>
    <Card className="soft-card mt-6 rounded-2xl"><CardContent className="p-6"><div className="flex items-end justify-between"><div><p className="eyebrow">By category</p><h2 className="mt-1 text-lg font-bold">カテゴリ別パフォーマンス</h2></div><span className="mono text-[10px] text-muted-foreground">{categories.length} categories</span></div>{categories.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="pb-3">カテゴリ</th><th className="pb-3 text-right">投稿数</th><th className="pb-3 text-right">インプレッション</th><th className="pb-3 text-right">エンゲージメント</th><th className="pb-3 text-right">ER</th></tr></thead><tbody>{categories.map((category, index) => <tr key={category.category} className="border-t border-border/60"><td className="py-4"><span className="mr-2 inline-block h-2 w-2 rounded-full" style={{ background: categoryColors[index % categoryColors.length] }} /> <span className="text-sm font-semibold">{category.category}</span></td><td className="py-4 text-right text-sm">{category.posts}</td><td className="py-4 text-right text-sm">{formatNumber(category.impressions)}</td><td className="py-4 text-right text-sm">{formatNumber(category.engagements)}</td><td className="py-4 text-right text-sm font-semibold text-primary">{rate(category.engagementRate)}</td></tr>)}</tbody></table></div> : <p className="mt-5 text-sm text-muted-foreground">実績を記録するとカテゴリ別の比較が表示されます。</p>}</CardContent></Card>
  </div>;
}

function Insight({ label, value, note }: { label: string; value: string; note: string }) { return <Card className="soft-card rounded-2xl"><CardContent className="p-5"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="metric-number mt-4 truncate text-2xl font-bold">{value}</p><p className="mt-2 text-[11px] text-muted-foreground">{note}</p></CardContent></Card>; }
function ComparisonStrip({ summary, report }: { summary: any; report: any }) { const impressionDelta = report?.impressionChangePct; const engagementDelta = report?.engagementRateChangeBps ? report.engagementRateChangeBps / 100 : 0; const impressionGoal = summary?.impressionsTarget ? Math.round(((summary.impressions ?? 0) / summary.impressionsTarget) * 100) : 0; const engagementGoal = summary?.engagementRateTarget ? Math.round(((summary.engagementRate ?? 0) / summary.engagementRateTarget) * 100) : 0; const delta = (value: number | null | undefined, suffix: string) => value === null || value === undefined ? "前週比較は次回から" : `${value > 0 ? "+" : ""}${value}${suffix}`; return <Card className="soft-card mt-4 rounded-2xl"><CardContent className="grid divide-y divide-border/70 p-0 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="p-4"><p className="eyebrow">Week over week</p><p className="mt-2 text-sm font-bold">到達の前週比</p><p className={cn("mt-1 text-lg font-bold", (impressionDelta ?? 0) >= 0 ? "text-[#558151]" : "text-[#a75847]")}>{delta(impressionDelta, "%")}</p></div><div className="p-4"><p className="eyebrow">Response signal</p><p className="mt-2 text-sm font-bold">ERの前週差</p><p className={cn("mt-1 text-lg font-bold", engagementDelta >= 0 ? "text-[#558151]" : "text-[#a75847]")}>{report ? `${engagementDelta > 0 ? "+" : ""}${engagementDelta.toFixed(2)}pt` : "前週比較は次回から"}</p></div><div className="p-4"><p className="eyebrow">Goal reference</p><p className="mt-2 text-sm font-bold">KPI達成率</p><p className="mt-1 text-lg font-bold text-primary">到達 {impressionGoal}% <span className="text-muted-foreground">/ ER {engagementGoal}%</span></p></div></CardContent></Card>; }
function AnalysisNote({ icon: Icon, title, body }: { icon: typeof TrendingUp; title: string; body: string }) { return <div className="rounded-xl border border-border/70 bg-secondary/40 p-4"><Icon className="h-4 w-4 text-primary" /><p className="mt-2 text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{body}</p></div>; }

function WeeklyReportPanel({ report, generating, onGenerate }: { report: any; generating: boolean; onGenerate: () => void }) {
  const rangeEnd = report ? new Date(new Date(report.weekEnd).getTime() - 24 * 60 * 60 * 1000) : null;
  const [, setLocation] = useLocation();
  return <Card className="soft-card mt-6 overflow-hidden rounded-2xl"><CardContent className="p-0"><div className="flex flex-col gap-4 border-b border-border/70 bg-[linear-gradient(120deg,#eef3f6,transparent_60%,#fbf2df)] px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Weekly intelligence</p><h2 className="mt-1 text-xl font-bold">週次分析レポート</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground">前週の実績を集計し、良かった点と次に試す一手を手動で振り返ります。</p></div><Badge className="rounded-full border-0 bg-[#e2edf6] px-3 py-1 text-[10px] text-[#49657e]">手動生成</Badge></div>{report ? <div className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="mono text-[10px] uppercase tracking-wider text-muted-foreground">{formatDate(report.weekStart)} — {rangeEnd && formatDate(rangeEnd)} / {report.source === "scheduled" ? "Scheduled" : "Manual"}</p><h3 className="editorial-title mt-2 text-2xl font-bold leading-snug">{report.insights.headline}</h3><p className="mt-2 max-w-3xl text-sm leading-7 text-muted-foreground">{report.insights.summary}</p></div><div className="grid grid-cols-3 gap-2 sm:min-w-[250px]"><ReportMetric label="投稿" value={`${report.postCount}`} /><ReportMetric label="表示" value={formatNumber(report.impressions)} /><ReportMetric label="ER" value={rate(report.engagementRateBps / 100)} /></div></div><div className="mt-6 grid gap-4 lg:grid-cols-3"><ReportList title="良かった点" items={report.insights.wins} tone="green" actionLabel="ネタを見直す" onAction={() => setLocation("/ideas")} /><ReportList title="確認したい点" items={report.insights.risks} tone="gold" actionLabel="運用ルールを開く" onAction={() => setLocation("/settings")} /><ReportList title="次週のアクション" items={report.insights.actions} tone="blue" actionLabel="実績を記録する" onAction={() => setLocation("/results")} /></div>{report.categoryBreakdown.length ? <div className="mt-6 border-t border-border/70 pt-5"><p className="eyebrow">Category signal</p><div className="mt-3 flex flex-wrap gap-2">{report.categoryBreakdown.map((category: any) => <span key={category.category} className="rounded-full border border-border bg-secondary/60 px-3 py-1.5 text-[11px]"><strong>{category.category}</strong><span className="ml-2 text-muted-foreground">{category.posts}件 / ER {rate(category.engagementRate)}</span></span>)}</div></div> : null}</div> : <div className="p-6"><EmptyState title="最初の週次レポートを作りましょう" description="投稿実績を記録したら、前週のKPI・傾向・次週のアクションを一つのレポートにまとめられます。" action={<Button onClick={onGenerate} disabled={generating} size="sm"><WandSparkles className="mr-2 h-4 w-4" />週次レポートを生成</Button>} /></div>}</CardContent></Card>;
}

function WeeklyRunHistory({ runs, retrying, onRetry }: { runs: any[]; retrying: boolean; onRetry: () => void }) {
  const latest = runs[0]; const statusStyle: Record<string, string> = { succeeded: "bg-[#e6f0e3] text-[#558151]", failed: "bg-[#f7e4df] text-[#a75847]", running: "bg-[#e2edf6] text-[#49657e]", skipped: "bg-[#f7edd8] text-[#a57528]" }; const statusLabel: Record<string, string> = { succeeded: "完了", failed: "失敗", running: "実行中", skipped: "スキップ" };
  return <Card className="soft-card mt-4 rounded-2xl"><CardContent className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Automation health</p><h2 className="mt-1 text-sm font-bold">週次レポートの実行履歴</h2><p className="mt-1 text-xs text-muted-foreground">手動生成・再試行・公開後の定期実行をここで確認できます。</p></div>{latest?.status === "failed" ? <Button onClick={onRetry} disabled={retrying} size="sm" variant="outline" className="rounded-lg border-[#d8a095] text-[#a75847]">{retrying ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <WandSparkles className="mr-1.5 h-3.5 w-3.5" />}再試行する</Button> : null}</div>{runs.length ? <div className="mt-4 space-y-2">{runs.slice(0, 4).map(run => <div key={run.id} className="flex flex-col gap-2 rounded-xl border border-border/70 bg-secondary/35 px-3 py-2.5 sm:flex-row sm:items-center"><Badge className={cn("w-fit rounded-full border-0 px-2 py-0.5 text-[10px]", statusStyle[run.status] ?? statusStyle.running)}>{statusLabel[run.status] ?? run.status}</Badge><span className="text-xs font-semibold">{run.trigger === "scheduled" ? "定期生成" : run.trigger === "retry" ? "再試行" : "手動生成"}</span><span className="text-[11px] text-muted-foreground">{new Date(run.startedAt).toLocaleString("ja-JP")}</span>{run.error ? <span className="text-[11px] text-[#a75847]">{run.error}</span> : null}</div>)}</div> : <p className="mt-4 rounded-xl bg-secondary/50 p-3 text-xs text-muted-foreground">まだ実行履歴はありません。週次レポートを生成すると、結果と失敗状態がここに残ります。</p>}</CardContent></Card>;
}

function ReportMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border/70 bg-card/70 px-3 py-2 text-center"><p className="mono text-[9px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
function ReportList({ title, items, tone, actionLabel, onAction }: { title: string; items: string[]; tone: "green" | "gold" | "blue"; actionLabel: string; onAction: () => void }) { const tones = { green: "border-[#cfe1ca] bg-[#f2f8f0]", gold: "border-[#ecd8ae] bg-[#fcf8ed]", blue: "border-[#cddbe6] bg-[#f3f7fa]" }; return <div className={cn("rounded-xl border p-4", tones[tone])}><p className="text-xs font-bold">{title}</p><ul className="mt-3 space-y-2 text-[11px] leading-relaxed text-muted-foreground">{items.map(item => <li key={item}>・{item}</li>)}</ul><button onClick={onAction} className="mt-4 inline-flex items-center text-[11px] font-semibold text-primary">{actionLabel}<ArrowRight className="ml-1 h-3.5 w-3.5" /></button></div>; }
