import React, { useEffect, useState } from "react";
import { CalendarClock, CheckCircle2, Clock3, Loader2, Pencil, RefreshCw, XCircle } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";

type ScheduledPost = { id: number; content: string; scheduledFor: Date | string; timezone: string; status: "scheduled" | "publishing" | "published" | "failed" | "cancelled"; xPostId: string | null; lastError: string | null };
const labels = { scheduled: "予約済み", publishing: "送信中", published: "送信済み", failed: "失敗", cancelled: "取消済み" } as const;
const tones = { scheduled: "bg-[#eaf0fb] text-[#49657e]", publishing: "bg-[#fcf8ed] text-[#745b2a]", published: "bg-[#e6f0e3] text-[#558151]", failed: "bg-destructive/10 text-destructive", cancelled: "bg-secondary text-muted-foreground" } as const;

function formatDate(value: Date | string) { return new Intl.DateTimeFormat("ja-JP", { month: "short", day: "numeric", weekday: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function toLocalInput(value: Date | string) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }

export function ScheduledPostsPanel() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const posts = trpc.growth.scheduledPosts.list.useQuery(undefined, { enabled: isAuthenticated });
  const runs = trpc.growth.scheduledPosts.runs.useQuery(undefined, { enabled: isAuthenticated });
  const [editing, setEditing] = useState<ScheduledPost | null>(null);
  const [content, setContent] = useState(""); const [scheduledFor, setScheduledFor] = useState("");
  useEffect(() => { if (!editing) return; setContent(editing.content); setScheduledFor(toLocalInput(editing.status === "failed" ? new Date(Date.now() + 5 * 60_000) : editing.scheduledFor)); }, [editing]);
  const refresh = () => { utils.growth.scheduledPosts.list.invalidate(); utils.growth.scheduledPosts.runs.invalidate(); };
  const cancel = trpc.growth.scheduledPosts.cancel.useMutation({ onSuccess: () => { refresh(); toast.success("予約投稿を取り消しました。"); }, onError: error => toast.error(error.message) });
  const update = trpc.growth.scheduledPosts.update.useMutation({ onSuccess: () => { refresh(); setEditing(null); toast.success("予約投稿を更新しました。"); }, onError: error => toast.error(error.message) });
  const retry = trpc.growth.scheduledPosts.retry.useMutation({ onSuccess: () => { refresh(); setEditing(null); toast.success("予約投稿を再試行として登録しました。"); }, onError: error => toast.error(error.message) });
  const groupedRuns = new Map<number, typeof runs.data>();
  runs.data?.forEach(run => groupedRuns.set(run.scheduledPostId, [...(groupedRuns.get(run.scheduledPostId) ?? []), run]));
  const visiblePosts = posts.data?.filter(post => post.status !== "cancelled" || new Date(post.scheduledFor).getTime() > Date.now() - 7 * 24 * 60 * 60_000) ?? [];

  return <Card className="soft-card mt-6 rounded-2xl"><CardContent className="p-5 sm:p-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Scheduled posts</p><h2 className="mt-1 text-lg font-bold">X投稿の予約一覧</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">投稿案の「Xへ予約」から作成した投稿を管理します。日時になると毎分確認され、安全に送信されます。</p></div><Badge className="w-fit rounded-full border-0 bg-[#eaf0fb] text-[#49657e]">{visiblePosts.filter(post => post.status === "scheduled").length} 件予約中</Badge></div>
    {posts.isLoading && isAuthenticated ? <div className="mt-5 flex items-center gap-2 rounded-xl border border-border/60 bg-card/70 p-4 text-xs text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin text-primary" />予約投稿を読み込んでいます。</div> : visiblePosts.length ? <div className="mt-5 space-y-3">{visiblePosts.map(post => { const history = groupedRuns.get(post.id) ?? []; const latestRun = history[0]; const runStatusLabel = latestRun?.status === "succeeded" ? "送信成功" : latestRun?.status === "failed" ? "送信失敗" : "実行中"; const runTriggerLabel = latestRun?.trigger === "retry" ? "再試行" : "定刻実行"; return <div key={post.id} className="rounded-xl border border-border/70 bg-card/70 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge className={`rounded-full border-0 ${tones[post.status]}`}>{labels[post.status]}</Badge><span className="flex items-center gap-1 text-[11px] font-medium text-muted-foreground"><Clock3 className="h-3.5 w-3.5" />{formatDate(post.scheduledFor)} ({post.timezone})</span></div><p className="mt-2 line-clamp-2 whitespace-pre-wrap text-sm leading-6">{post.content}</p>{post.lastError ? <p className="mt-2 text-[11px] leading-relaxed text-destructive">失敗理由：{post.lastError}</p> : null}{post.status === "published" && post.xPostId ? <a className="mt-2 inline-flex items-center gap-1 text-[11px] font-semibold text-primary hover:underline" href={`https://x.com/i/web/status/${post.xPostId}`} target="_blank" rel="noreferrer"><CheckCircle2 className="h-3.5 w-3.5" />Xの投稿を開く</a> : null}{latestRun ? <p className="mt-2 text-[10px] text-muted-foreground">実行履歴：{runTriggerLabel}・{runStatusLabel}（{formatDate(latestRun.startedAt)}）</p> : null}</div><div className="flex shrink-0 flex-wrap gap-2">{post.status === "scheduled" ? <><Button size="sm" variant="outline" onClick={() => setEditing(post)} className="rounded-lg bg-card"><Pencil className="mr-1.5 h-3.5 w-3.5" />編集</Button><Button size="sm" variant="ghost" onClick={() => { if (window.confirm("この予約投稿を取り消しますか？")) cancel.mutate({ id: post.id }); }} disabled={cancel.isPending} className="rounded-lg text-destructive hover:bg-destructive/10 hover:text-destructive"><XCircle className="mr-1.5 h-3.5 w-3.5" />取消</Button></> : null}{post.status === "failed" ? <Button size="sm" variant="outline" onClick={() => setEditing(post)} className="rounded-lg border-[#d7c38f] bg-[#fcf8ed] text-[#745b2a]"><RefreshCw className="mr-1.5 h-3.5 w-3.5" />再試行</Button> : null}</div></div></div>; })}</div> : <div className="mt-5 rounded-xl border border-dashed border-border bg-card/45 p-7 text-center"><CalendarClock className="mx-auto h-6 w-6 text-primary" /><p className="mt-3 text-sm font-semibold">予約投稿はまだありません</p><p className="mt-1 text-xs text-muted-foreground">投稿案画面で内容を確認してから「Xへ予約」を選ぶと、ここで日時と送信状況を管理できます。</p></div>}
    <Dialog open={Boolean(editing)} onOpenChange={next => { if (!next) setEditing(null); }}><DialogContent className="max-w-xl rounded-2xl"><DialogHeader><p className="eyebrow">{editing?.status === "failed" ? "Retry scheduled post" : "Edit scheduled post"}</p><DialogTitle className="editorial-title text-2xl">{editing?.status === "failed" ? "予約投稿を再試行する" : "予約投稿を編集する"}</DialogTitle><DialogDescription>{editing?.status === "failed" ? "新しい日時を指定して、失敗した投稿を再度予約します。" : "投稿内容と日時を変更できます。送信開始後は編集できません。"}</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><div><Label className="text-xs">投稿内容</Label><Textarea value={content} onChange={event => setContent(event.target.value)} rows={6} disabled={editing?.status === "failed"} className="mt-2" /></div><div><Label className="text-xs">予約日時</Label><Input type="datetime-local" value={scheduledFor} min={toLocalInput(new Date(Date.now() + 60_000))} onChange={event => setScheduledFor(event.target.value)} className="mt-2" /></div></div><DialogFooter><Button variant="ghost" onClick={() => setEditing(null)}>キャンセル</Button><Button onClick={() => editing?.status === "failed" ? retry.mutate({ id: editing.id, scheduledFor: new Date(scheduledFor) }) : update.mutate({ id: editing!.id, content, scheduledFor: new Date(scheduledFor), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "Asia/Tokyo" })} disabled={!editing || !content.trim() || Array.from(content).length > 280 || !scheduledFor || update.isPending || retry.isPending} className="rounded-xl">{update.isPending || retry.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <CalendarClock className="mr-2 h-4 w-4" />}{editing?.status === "failed" ? "再試行を予約" : "変更を保存"}</Button></DialogFooter></DialogContent></Dialog>
  </CardContent></Card>;
}
